config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'check_lists#index'

  resources :forms do
    resources :form_questions
    member do
      put :publish
    end
  end

  resources :check_lists, except: [:show, :new]
  resources :users
end

app/models/check_list.rb
class CheckList < ApplicationRecord
  belongs_to :form
  belongs_to :user

  has_many :answers, dependent: :destroy

  validates :project_uid, presence: true
  validate :form_is_published

  delegate :title, :description, to: :form

  before_create :initialize_answers

  accepts_nested_attributes_for :answers

  private

  def initialize_answers
    form.form_questions.each do |question|
      answers << Answer.new(form_question: question, user: user)
    end
  end

  def form_is_published
    return unless form

    unless form.published?
      errors.add(:form, 'Must be published')
    end
  end
end

app/controllers/check_lists_controller.rb
class CheckListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_check_list, only: [:show, :edit, :update, :destroy]

  def index
    @check_list = current_user.check_lists.new
    prepare_data_for_index
  end

  def edit
    authorize @check_list
  end

  def create
    @check_list = CheckList.new(check_list_create_params)
    @check_list.user = current_user

    authorize @check_list

    if @check_list.save
      render({action: :edit}, {notice: I18n.t('controllers.checklist.created')})
    else
      prepare_data_for_index
      render :index
    end
  end

  def update
    authorize @check_list

    @check_list.assign_attributes(check_list_update_params)
    @check_list.answers.each do |answer|
      answer.user = current_user if answer.changed?
    end

    if @check_list.save
      redirect_to({action: :index}, {notice: I18n.t('controllers.checklist.updated')})
    else
      render :edit
    end
  end

  def destroy
    authorize @check_list

    @check_list.destroy
    redirect_to check_lists_url, notice: I18n.t('controllers.checklist.destroyed')
  end

  private

  def prepare_data_for_index
    @check_lists = policy_scope(CheckList)
    @forms = Form.published.select(:id, :title).order(:title).all
  end

  def set_check_list
    @check_list = CheckList.find(params[:id])
  end

  def check_list_create_params
    params.require(:check_list).permit(:project_uid, :form_id)
  end

  def check_list_update_params
    params.require(:check_list).permit(answers_attributes: [:id, :response, :comment])
  end
end

app/helpers/check_lists_helper.rb
module CheckListsHelper
  def percents_of_answers(check_list)
    answers = check_list.answers.pluck(:response)

    total_count = answers.count.to_f
    if total_count == 0
      return {
        absent: 0,
        yes: 0,
        no: 0,
        na: 0,
      }
    end

    {
      absent: (answers.count('absent') / total_count * 100).round,
      yes: (answers.count('yes') / total_count * 100).round,
      no: (answers.count('no') / total_count * 100).round,
      na: (answers.count('na') / total_count * 100).round,
    }
  end
end

app/views/check_lists/_fill_check_list.html.erb
<%= form_with(model: @check_list, local: true) do |form| %>
  <%= render partial: 'partials/form_errors', locals: {model: @check_list} %>

  <div id="checklist-form">
  <div class="form-group">
    <%= form.label :project_uid %>
    <%= form.text_field :project_uid %>
  </div>

  <div class="form-group">
    <%= form.label 'Select checklist to fill' %>
    <%= form.select :form_id, @forms.map { |f| [f.title, f.id] } %><br>
    <button type="button" class="btn" id="cancel-button">Cancel</button>
    <%= form.submit 'FILLIN', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/check_lists/_form.html.erb
<%= form_with(model: check_list, local: true) do |form| %>
  <%= render partial: 'partials/form_errors', locals: {model: check_list} %>

  <div class="actions btn">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>

  <%= form.fields_for :answers do |answer_form| %>
    <div class="container">
      <div class="card">
        <div class="card-body">
          <div class="row col-xs-5">
            <%= answer_form.object.title %><br>
            <%= answer_form.object.description %>
          </div>
          <div class="row col-xs-2">
            <%= answer_form.select :response, Answer.responses.map { |key, value| [key.humanize, key] } %>
          </div>
          <div class="row col-xs-5">
            <%= answer_form.label :comment %>
            <%= answer_form.text_area :comment, class: 'text-area', placeholder: 'Could you please enter your comment' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/check_lists/edit.html.erb
<div class="button fa fa-arrow-left fa-lg">
  <%= link_to 'Back', check_lists_path, class: "btn btn-outline-dark", data: { confirm: 'Are you sure?' } %>
</div>

<div class="container">
  <div class="row">
    <div class="title col-md-10">
      <h1><%= @check_list.title %></h1>
  	  <h5><%= @check_list.description %></h5>
    </div>
  </div>
</div>

<%= render 'form', check_list: @check_list %>

app/views/check_lists/index.html.erb
<h1>Check Lists</h1>

<button type="button" class="btn btn-primary" id="checklist-button">Fill checklist</button>

<div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th scope="col" class="center">Project</th>
      <th scope="col" class="center">Checklist</th>
      <th scope="col">Updated</th>
      <th scope="col">Questions</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
      <% @check_lists.each do |check_list| %>
        <tr>
          <td><%= check_list.project_uid %></td>
          <td><%= check_list.title %></td>
          <td><%= check_list.updated_at.strftime('%d.%m.%Y') %></td>
          <td>
            <% p = percents_of_answers(check_list) %>
            <div style="width: 100%">
              <div class="bg-secondary color-strip" style="width: <%= p[:absent] %>%;"></div>
              <div class="color-strip" style="width: <%= p[:na] %>%; background-color: purple"></div>
              <div class="bg-success color-strip" style="width: <%= p[:yes] %>%;"></div>
              <div class="bg-danger color-strip" style="width: <%= p[:no] %>%;"></div>
            </div>
          </td>
          <td>
            <%= link_to fa_icon('pencil'), edit_check_list_path(check_list), class: 'middle-button' %>
            
            <div class="dropdown list-button">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-ellipsis-v"></i>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to fa_icon('trash', text: 'Remove'), check_list, method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
              </ul> 
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'fill_check_list', check_list: @check_list %>