config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'check_lists#index'

  resources :forms do
    resources :form_questions
    member do
      put :publish
    end
  end

  resources :check_lists, except: [:show, :new]
  resources :users
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  before_action :set_form, only: [:show, :edit, :update, :publish, :destroy]

  def index
    @forms = policy_scope(Form)
  end

  def show
    authorize @form
  end

  def new
    @form = Form.new
    @form.form_questions.build

    authorize @form
  end

  def edit
    @form.form_questions.build

    authorize @form
  end

  def create
    @form = Form.new(form_params)
    @form.user = current_user

    authorize @form

    if @form.save
      redirect_to forms_path, notice: I18n.t('controllers.form.created')
    else
      render :new
    end
  end

  def update
    authorize @form

    if @form.update(form_params)
      redirect_to forms_path, notice: I18n.t('controllers.form.updated')
    else
      render :edit
    end
  end

  def publish
    authorize @form

    @form.publish!

    redirect_to({action: :index}, {notice: I18n.t('controllers.form.published')})
  end


  def destroy
    authorize @form

    @form.destroy
    redirect_to forms_url, notice: I18n.t('controllers.form.destroyed')
  end

  private

  def set_form
    @form = Form.find(params[:id])
  end

  def form_params
    params.require(:form).permit(:title, :description, form_questions_attributes: [:id, :title, :description, :_destroy])
  end
end

app/helpers/forms_helper.rb
module FormsHelper
  def form_status_text(form)
    if form.published?
      'Published'
    else
      "Draft (#{form.updated_at.strftime('%d.%m.%Y')})"
    end
  end

  def form_published_text(form)
    if form.published?
      form.published_at.strftime('%d.%m.%Y')
    else
      "Not published"
    end
  end
end

app/views/forms/_form.html.erb
<%= form_with(model: form, local: true) do |form| %>
  <%= render partial: 'partials/form_errors', locals: {model: @form} %>

  <div class="container">
    <div class="actions list-button">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
    <div class="row">
      <div class="col-md-5 offset-md-3 mb-3">
        <%= form.text_field :title, class: 'form-control form-control-lg placeholder', type: 'text', placeholder: 'Form title' %>
      </div>
    </div>
      
    <div class="row">
      <div class="col-md-8 offset-md-2 mb-3">
        <%= form.text_field :description, class: 'form-control', type: 'text', placeholder: 'Form detailed description'%>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <%= form.fields_for :form_questions do |form_question| %>
          <%= render 'form_question_fields', f: form_question %>
        <% end %>
      </div>
    </div>
    <div class="btn form-button">
      <%= link_to_add_association '', form, :form_questions, class: 'fa fa-plus-circle fa-lg', data: { association_insertion_method: :append } %>
    </div>
  </div>
<% end %>

app/views/forms/_form_question_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
  <%= f.text_field :title, class: 'form-control col-md-8 mb-3 border', type: 'text', placeholder: 'Question text?' %>
  <%= f.text_field :description, class: 'form-control col-md-10 border', type: 'text', placeholder: 'Question detailed description' %>
  <div class="btn list-button">
	<%= link_to_remove_association '', f, data: { confirm: 'Are you sure?' }, class: 'fa fa-times-circle fa-lg'%>
  </div>
</div>
 

app/views/forms/edit.html.erb
<div class="button fa fa-arrow-left fa-lg">
  <%= link_to 'Back', forms_path, class: "btn btn-outline-dark", data: { confirm: 'Are you sure?' } %>
</div>

<h1>Editing Form</h1>

<%= render 'form', form: @form %>

app/views/forms/index.html.erb
<h1>Forms</h1>

<%= link_to 'New Form', new_form_path, class: 'btn btn-primary form-btn' %>

<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col" class="center">Name</th>
    <th scope="col" class="center">Description</th>
    <th scope="col">Status</th>
    <th scope="col">Published</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
    <tbody>
       <% @forms.each do |form| %>
        <tr>
          <td><%= form.title %></td>
          <td><%= form.description %></td>
          <td><%= form_status_text(form) %></td>
          <td><%= form_published_text(form) %></td>
          <td>
            <%= link_to fa_icon('pencil'), edit_form_path(form), class: 'middle-button' if policy(form).edit?  %>
            <div class="btn-group list-button">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-ellipsis-v"></i>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to fa_icon('info', text: 'Show'), form_path(form) if policy(form).show? %>
                </li>
                <li>  
                  <%= link_to fa_icon('eye', text: 'Publish'), publish_form_path(form), method: :put if policy(form).publish?  %>
                </li>
                <li>  
                  <%= link_to fa_icon('trash', text: 'Remove'), form, method: :delete, data: { confirm: 'Are you sure?' } if policy(form).destroy? %>
                </li>
              </ul>
            </div>      
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/forms/new.html.erb
<div class="button fa fa-arrow-left fa-lg">
  <%= link_to 'Back', forms_path, class: "btn btn-outline-dark" %>
</div>

<h1>New Form</h1>

<%= render 'form', form: @form %>

app/views/forms/show.html.erb
<div class="button fa fa-arrow-left fa-lg">
  <%= link_to 'Back', forms_path, class: "btn btn-outline-dark" %>
</div>

<h2>Form Questions</h2>

<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Description</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
    <tbody>
      <% @form.form_questions.each do |q| %>
        <tr>
          <td><%= q.title %></td>
          <td><%= q.description %></td>
          <td>
            <%= link_to 'Edit', edit_form_form_question_path(@form, q), class: 'block-link' if policy(q).edit? %>
            <%= link_to 'Destroy', form_form_question_path(@form, q), method: :delete, data: { confirm: 'Are you sure?' } if policy(q).destroy? %>
        </td>
        </tr>
      <% end %>
    </tbody>
</table>